using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WM_Plane_CreateDBImport.Model
{
    public class KingData
    {
        int id;
        Aimms animms;
        Arinc429 arinc429;
        Bjwmo bjwmo;
        Icedet icedet;
        Inletcontroldata inletcontroldata;
        M300TAS m300TAS;
        Nev nev;
        Pcasp pcasp;
        PcaspSimple2 pcasp_Simple2;
        Tracegas tracegas;
        //#region animms
        //public DateTime dateTime;
        //public float Latitude, Longitude;
        //public float TAS;
        //public double Id0Count;
        //public String Time;
        //public float Temp;
        //public float RH;
        //public float BaroPress;
        //public float WindFlowNS;
        //public float WindFlowEW;
        //public float WindSpeed;
        //public float WindDir;
        //public string WindSolution;

        //public float BaroPress_aimms_1;
        //public float WindSpeed_aimms_1;
        //public float Altitude;
        //public double Id1Count;
        //public string Time_aimms_1;
        //public float Latitude_aimms_1;
        //public float Longitude_aimms_1;
        //public float Altitude_aimms_1;
        //public float VelocityNS;
        //public float VelocityEW;
        //public float VelocityUD;
        //public float Roll;
        //public float Pitch;
        //public float Yaw;
        //public float TAS_aimms_1;
        //public float VerticalWind;
        //public float Sideslip;
        //public float AOAPressDiff;
        //public float SideslipDiff;
        //public string Latitude_aimms_2;
        //public string Longitude_aimms_2;
        //public float Altitude_aimms_2;
        //public float Id2Count;
        //public float Time_aimms_2;
        //public float Latitude_aimms_3;
        //public float Longitude_aimms_3;
        //public float Altitude_aimms_3;
        //public float GroundSpeed;
        //public float GroundTrack;
        //public float HFOM;
        //public float VFOM;
        //public double NavMode;
        //public float Satellites;
        //public float DatumNumber;
        //public string SolConfLevel;
        //public string GPSTimeAlign;
        //public string NavModeStatus;
        //public string Latitude_aimms_4;
        //public string Longitude_aimms_4;
        //public float Altitude_aimms_4;
        //public float Latitude_aimms_5;
        //public float Longitude_aimms_5;
        //#endregion
        //#region arinc429
        //public DateTime DateTime_arinc429_1;
        //public float StaticPSSECorrected;
        //public float ImpactPressure;
        //public float Altitude_arinc429_1;
        //public float BaroCorrectedAltitude;
        //public float Mach;
        //public float Airspeed;
        //public float TrueAirSpeed;
        //public float Totaltemp;
        //public float StaticTemp;
        //public float veritcalSpeed;
        //public float magheadingdeg;
        //#endregion
        //#region bjwmo
        //public DateTime Date;
        //public string AIMMSTime;
        //public float Latitude_bjwmo_1;
        //public float Longitude_bjwmo_1;
        //public float LWC;
        //public float TWC;
        //public float Hygrometer;
        //public float RICEMsoFreqHz;
        //public float RMTTotalTempC;
        //public float RMTStaticTempC;
        //public float DewPointC;
        //public float TAS_bjwmo_1;
        //public float Temp_bjwmo_1;
        //public float RH_bjwmo_1;
        //public float WindFlowNS_bjwmo_1;
        //public float WindFlowEW_bjwmo_1;
        //public float WindSpeed_bjwmo_1;
        //public float WindDir_bjwmo_1;
        //public string WindSolution_bjwmo_1;
        //public float BaroPress_bjwmo_1;
        //public float WindSpeed_bjwmo_2;
        //public float Altitude_bjwmo_1;
        //public float Latitude_bjwmo_2;
        //public float Longitude_bjwmo_2;
        //public float Altitude_bjwmo_2;
        //public float VelocityNS_bjwmo_1;
        //public float VelocityEW_bjwmo_1;
        //public float VelocityUD_bjwmo_1;
        //public float Roll_bjwmo_1;
        //public float Pitch_bjwmo_1;
        //public float Yaw_bjwmo_1;
        //public float TAS_bjwmo_2;
        //public float VerticalWind_bjwmo_1;
        //public float Sideslip_bjwmo_1;
        //public float AOAPressDiff_bjwmo_1;
        //public float SideslipDiff_bjwmo_1;
        //public string Latitude_bjwmo_3;
        //public string Longitude_bjwmo_3;
        //public float Altitude_bjwmo_3;
        //public float StaticPSSECorrected_bjwmo_1;
        //public float StaticPSSECorrected_bjwmo_2;

        //#endregion 字段列表
        //#region Icedet
        //public DateTime DateTime_icedet_1;
        //public string ID_W;
        //public double OnTimeCntr;
        //public double Power;
        //public string PermErr1;
        //public string PermErr2;
        //public string PermErr3;
        //public double TotIceCnt;
        //public string ID_X;
        //public double MsoFreq;
        //public double IceCycCnt;
        //public string SigState;
        //public string OprState;
        //public string BitErr1;
        //public string BitErr2;
        //public string BitErr3;
        //public string ID_Y;
        //public double TotFailCnt;
        //public double MsoFailCnt;
        //public double IceFailCnt;
        //public double StaFailCnt;
        //public double HtrFailCnt;
        //public string ID_Z;
        //public string FaultLog1;
        //public string FaultLog2;
        //public string FaultLog3;
        //public string FaultLog4;
        //public string FaultLog5;
        //public string FaultLog6;
        //public string FaultLog7;
        //#endregion
        //#region inletcontroldata
        //public DateTime DateTime_inletcontroldata_1;
        //public float tip_flow;
        //public float tipfltrg;
        //public float airspeed_inletcontroldata_1;
        //public float oat_temp;
        //public float instflow;
        //public float inltpres;
        //public float blwrflow;
        //public float blwrtarg;
        //public float blwr_tmp;
        //public float blwr_pwr;
        //public float throtpos;
        //public float fconetmp;
        //public float rconetmp;
        //public float pylontmp;
        //public float sensrtmp;
        //public float fconepwr;
        //public float rconepwr;
        //public float pylonpwr;
        //public float sensrpwr;
        //#endregion
        //#region m300tas
        //public DateTime DateTime_m300TAS_1;
        //public float ARINCTAS;
        //#endregion
        //#region nev
        //public DateTime DateTime_nev_1;
        //public float ARINCAltitudeft;
        //public float NevTWC;
        //public float NevLWC;
        //#endregion
        //#region pcasp
        //public DateTime DateTime_pcasp_1;
        //public float Analog0;
        //public float Analog1;
        //public float Analog2;
        //public float Analog3;
        //public float Analog4;
        //public float Analog5;
        //public float Analog6;
        //public float Analog7;
        //public float HighGainBaselinev;
        //public float MidGainBaselinev;
        //public float LowGainBaselinev;
        //public float SampleFlow;
        //public float LaserReferencev;
        //public float Analog1v;
        //public float SheathFlow;
        //public float InternalTemp;
        //public float AvgTransit;
        //public float AvgTransit_pcasp_1;
        //public float FIFOFull;
        //public float ResetFlag;
        //public float SynsErrorA;
        //public float SyncErrorB;
        //public float SyncErrorC;
        //public float Overrange;
        //public float SPPSamples;
        //public float RangeValue;
        //public float RangeControl;
        //public float Range;
        //public float LasereReferencev;
        //public float Channel_1;
        //public float Channel_2;
        //public float Channel_3;
        //public float Channel_4;
        //public float Channel_5;
        //public float Channel_6;
        //public float Channel_7;
        //public float Channel_8;
        //public float Channel_9;
        //public float Channel_10;
        //public float Channel_11;
        //public float Channel_12;
        //public float Channel_13;
        //public float Channel_14;
        //public float Channel_15;
        //public float Channel_16;
        //public float Channel_17;
        //public float Channel_18;
        //public float Channel_19;
        //public float Channel_20;
        //public float Channel_21;
        //public float Channel_22;
        //public float Channel_23;
        //public float Channel_24;
        //public float Channel_25;
        //public float Channel_26;
        //public float Channel_27;
        //public float Channel_28;
        //public float Channel_29;
        //public float Channel_30;
        //public float MidSizes_1;
        //public float MidSizes_2;
        //public float MidSizes_3;
        //public float MidSizes_4;
        //public float MidSizes_5;
        //public float MidSizes_6;
        //public float MidSizes_7;
        //public float MidSizes_8;
        //public float MidSizes_9;
        //public float MidSizes_10;
        //public float MidSizes_11;
        //public float MidSizes_12;
        //public float MidSizes_13;
        //public float MidSizes_14;
        //public float MidSizes_15;
        //public float MidSizes_16;
        //public float MidSizes_17;
        //public float MidSizes_18;
        //public float MidSizes_19;
        //public float MidSizes_20;
        //public float MidSizes_21;
        //public float MidSizes_22;
        //public float MidSizes_23;
        //public float MidSizes_24;
        //public float MidSizes_25;
        //public float MidSizes_26;
        //public float MidSizes_27;
        //public float MidSizes_28;
        //public float MidSizes_29;
        //public float MidSizes_30;
        //public float Counts_1;
        //public float Counts_2;
        //public float Counts_3;
        //public float Counts_4;
        //public float Counts_5;
        //public float Counts_6;
        //public float Counts_7;
        //public float Counts_8;
        //public float Counts_9;
        //public float Counts_10;
        //public float Counts_11;
        //public float Counts_12;
        //public float Counts_13;
        //public float Counts_14;
        //public float Counts_15;
        //public float Counts_16;
        //public float Counts_17;
        //public float Counts_18;
        //public float Counts_19;
        //public float Counts_20;
        //public float Counts_21;
        //public float Counts_22;
        //public float Counts_23;
        //public float Counts_24;
        //public float Counts_25;
        //public float Counts_26;
        //public float Counts_27;
        //public float Counts_28;
        //public float Counts_29;
        //public float Counts_30;
        //public float ValidCounts;
        //public float MinSizes_1;
        //public float MinSizes_2;
        //public float MinSizes_3;
        //public float MinSizes_4;
        //public float MinSizes_5;
        //public float MinSizes_6;
        //public float MinSizes_7;
        //public float MinSizes_8;
        //public float MinSizes_9;
        //public float MinSizes_10;
        //public float MinSizes_11;
        //public float MinSizes_12;
        //public float MinSizes_13;
        //public float MinSizes_14;
        //public float MinSizes_15;
        //public float MinSizes_16;
        //public float MinSizes_17;
        //public float MinSizes_18;
        //public float MinSizes_19;
        //public float MinSizes_20;
        //public float MinSizes_21;
        //public float MinSizes_22;
        //public float MinSizes_23;
        //public float MinSizes_24;
        //public float MinSizes_25;
        //public float MinSizes_26;
        //public float MinSizes_27;
        //public float MinSizes_28;
        //public float MinSizes_29;
        //public float MinSizes_30;
        //public float MaxSizes_1;
        //public float MaxSizes_2;
        //public float MaxSizes_3;
        //public float MaxSizes_4;
        //public float MaxSizes_5;
        //public float MaxSizes_6;
        //public float MaxSizes_7;
        //public float MaxSizes_8;
        //public float MaxSizes_9;
        //public float MaxSizes_10;
        //public float MaxSizes_11;
        //public float MaxSizes_12;
        //public float MaxSizes_13;
        //public float MaxSizes_14;
        //public float MaxSizes_15;
        //public float MaxSizes_16;
        //public float MaxSizes_17;
        //public float MaxSizes_18;
        //public float MaxSizes_19;
        //public float MaxSizes_20;
        //public float MaxSizes_21;
        //public float MaxSizes_22;
        //public float MaxSizes_23;
        //public float MaxSizes_24;
        //public float MaxSizes_25;
        //public float MaxSizes_26;
        //public float MaxSizes_27;
        //public float MaxSizes_28;
        //public float MaxSizes_29;
        //public float MaxSizes_30;



        //#endregion
        //#region pcasp_simple2
        //public DateTime DateTime_pcasp_simple2_1;
        //public float Counts_pcasp_simple2_1_1;
        //public float Counts_pcasp_simple2_1_2;
        //public float Counts_pcasp_simple2_1_3;
        //public float Counts_pcasp_simple2_1_4;
        //public float Counts_pcasp_simple2_1_5;
        //public float Counts_pcasp_simple2_1_6;
        //public float Counts_pcasp_simple2_1_7;
        //public float Counts_pcasp_simple2_1_8;
        //public float Counts_pcasp_simple2_1_9;
        //public float Counts_pcasp_simple2_1_10;
        //public float Counts_pcasp_simple2_1_11;
        //public float Counts_pcasp_simple2_1_12;
        //public float Counts_pcasp_simple2_1_13;
        //public float Counts_pcasp_simple2_1_14;
        //public float Counts_pcasp_simple2_1_15;
        //public float Counts_pcasp_simple2_1_16;
        //public float Counts_pcasp_simple2_1_17;
        //public float Counts_pcasp_simple2_1_18;
        //public float Counts_pcasp_simple2_1_19;
        //public float Counts_pcasp_simple2_1_20;
        //public float Counts_pcasp_simple2_1_21;
        //public float Counts_pcasp_simple2_1_22;
        //public float Counts_pcasp_simple2_1_23;
        //public float Counts_pcasp_simple2_1_24;
        //public float Counts_pcasp_simple2_1_25;
        //public float Counts_pcasp_simple2_1_26;
        //public float Counts_pcasp_simple2_1_27;
        //public float Counts_pcasp_simple2_1_28;
        //public float Counts_pcasp_simple2_1_29;
        //public float Counts_pcasp_simple2_1_30;
        //public float SampleFlow_pcasp_simple2_1;
        //public float Altitudeft;
        //#endregion
        //#region tracegas
        //public DateTime DateTime_tracegas_1;
        //public DateTime DateTime_tracegas_2;
        //public float ARINCAltitudeft_tracegas_1;
        //public float ARINCStaticPmb;
        //public float RMTStaticC;
        //public float DPC;
        //public float O3;
        //public float NOX;
        //public float SO2;
        //public float H2O2;
        //public float CO;
        //public float O3_tracegas_1;
        //public float NOX_tracegas_1;
        //public float SO2_tracegas_1;
        //public float H2O2_tracegas_1;
        //public float CO_tracegas_1;
        //#endregion
    }
}
