using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using WM_Plane_KingData.Util;

namespace WM_Plane_KingData.Model
{
    public class Pcasp:ModelCommon
    {
        #region 字段列表
        public DateTime DateTime_pcasp_1;
        public float Analog0;
        public float Analog1;
        public float Analog2;
        public float Analog3;
        public float Analog4;
        public float Analog5;
        public float Analog6;
        public float Analog7;
        public float HighGainBaselinev;
        public float MidGainBaselinev;
        public float LowGainBaselinev;
        public float SampleFlow;
        public float LaserReferencev;
        public float Analog1v;
        public float SheathFlow;
        public float InternalTemp;
        public float AvgTransit;
        public float AvgTransit_pcasp_1;
        public float FIFOFull;
        public float ResetFlag;
        public float SynsErrorA;
        public float SyncErrorB;
        public float SyncErrorC;
        public float Overrange;
        public float SPPSamples;
        public float RangeValue;
        public float RangeControl;
        public float Range;
        public float LasereReferencev;
        public float Channel_1;
        public float Channel_2;
        public float Channel_3;
        public float Channel_4;
        public float Channel_5;
        public float Channel_6;
        public float Channel_7;
        public float Channel_8;
        public float Channel_9;
        public float Channel_10;
        public float Channel_11;
        public float Channel_12;
        public float Channel_13;
        public float Channel_14;
        public float Channel_15;
        public float Channel_16;
        public float Channel_17;
        public float Channel_18;
        public float Channel_19;
        public float Channel_20;
        public float Channel_21;
        public float Channel_22;
        public float Channel_23;
        public float Channel_24;
        public float Channel_25;
        public float Channel_26;
        public float Channel_27;
        public float Channel_28;
        public float Channel_29;
        public float Channel_30;
        public float MidSizes_1;
        public float MidSizes_2;
        public float MidSizes_3;
        public float MidSizes_4;
        public float MidSizes_5;
        public float MidSizes_6;
        public float MidSizes_7;
        public float MidSizes_8;
        public float MidSizes_9;
        public float MidSizes_10;
        public float MidSizes_11;
        public float MidSizes_12;
        public float MidSizes_13;
        public float MidSizes_14;
        public float MidSizes_15;
        public float MidSizes_16;
        public float MidSizes_17;
        public float MidSizes_18;
        public float MidSizes_19;
        public float MidSizes_20;
        public float MidSizes_21;
        public float MidSizes_22;
        public float MidSizes_23;
        public float MidSizes_24;
        public float MidSizes_25;
        public float MidSizes_26;
        public float MidSizes_27;
        public float MidSizes_28;
        public float MidSizes_29;
        public float MidSizes_30;
        public float Counts_1;
        public float Counts_2;
        public float Counts_3;
        public float Counts_4;
        public float Counts_5;
        public float Counts_6;
        public float Counts_7;
        public float Counts_8;
        public float Counts_9;
        public float Counts_10;
        public float Counts_11;
        public float Counts_12;
        public float Counts_13;
        public float Counts_14;
        public float Counts_15;
        public float Counts_16;
        public float Counts_17;
        public float Counts_18;
        public float Counts_19;
        public float Counts_20;
        public float Counts_21;
        public float Counts_22;
        public float Counts_23;
        public float Counts_24;
        public float Counts_25;
        public float Counts_26;
        public float Counts_27;
        public float Counts_28;
        public float Counts_29;
        public float Counts_30;
        public float ValidCounts;
        public float MinSizes_1;
        public float MinSizes_2;
        public float MinSizes_3;
        public float MinSizes_4;
        public float MinSizes_5;
        public float MinSizes_6;
        public float MinSizes_7;
        public float MinSizes_8;
        public float MinSizes_9;
        public float MinSizes_10;
        public float MinSizes_11;
        public float MinSizes_12;
        public float MinSizes_13;
        public float MinSizes_14;
        public float MinSizes_15;
        public float MinSizes_16;
        public float MinSizes_17;
        public float MinSizes_18;
        public float MinSizes_19;
        public float MinSizes_20;
        public float MinSizes_21;
        public float MinSizes_22;
        public float MinSizes_23;
        public float MinSizes_24;
        public float MinSizes_25;
        public float MinSizes_26;
        public float MinSizes_27;
        public float MinSizes_28;
        public float MinSizes_29;
        public float MinSizes_30;
        public float MaxSizes_1;
        public float MaxSizes_2;
        public float MaxSizes_3;
        public float MaxSizes_4;
        public float MaxSizes_5;
        public float MaxSizes_6;
        public float MaxSizes_7;
        public float MaxSizes_8;
        public float MaxSizes_9;
        public float MaxSizes_10;
        public float MaxSizes_11;
        public float MaxSizes_12;
        public float MaxSizes_13;
        public float MaxSizes_14;
        public float MaxSizes_15;
        public float MaxSizes_16;
        public float MaxSizes_17;
        public float MaxSizes_18;
        public float MaxSizes_19;
        public float MaxSizes_20;
        public float MaxSizes_21;
        public float MaxSizes_22;
        public float MaxSizes_23;
        public float MaxSizes_24;
        public float MaxSizes_25;
        public float MaxSizes_26;
        public float MaxSizes_27;
        public float MaxSizes_28;
        public float MaxSizes_29;
        public float MaxSizes_30;

        
    
        #endregion

        

        public DateTime GetDateTime()
        {
            return this.DateTime_pcasp_1;
        }
    }
}
